#!/usr/bin/env bash

# This is the Mumm-Ra script!
# Get ready to turn you machine into an awesome development one.
# Based on thoughtbot's awesome https://github.com/thoughtbot/laptop.

# The Incantation
echo
echo 'Ancient Spirits of Evil...'
echo "Transform $(hostname -s)'s decayed form..."
echo 'To Mumm-Ra, the Ever-living development machine!'
echo

read -r -s -p 'When ready, press any key to continue...' -n1 key
echo
echo

# Setting up Homebrew
if ! command -v 'brew' >/dev/null 2>&1; then
  echo -n 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" >/dev/null 2>&1
else
  echo -n 'Homebrew is already installed. Updating it...'
  brew update >/dev/null 2>&1
fi

echo ' done.'
echo

formulae=( 'tree' 'wget' 'unrar' 'rbenv' 'ruby-build' 'shellcheck' )

for formula in "${formulae[@]}"; do

  if ! command -v "${formula}" >/dev/null 2>&1; then
    echo -n "Installing ${formula}..."
  else
    echo -n "Updating ${formula}..."
  fi

  brew install "${formula}" >/dev/null 2>&1
  echo ' done.'
done


# Run local customizations, if any
customizations="${HOME}/.mumm-ra.local"

echo

if [[ -f "${customizations}" ]]; then
  echo "Now running your customizations from ${customizations}..."
  . "${customizations}"
  echo ' done.'
fi

echo
echo 'All good, enjoy!'
exit 0
