#!/usr/bin/env bash

# This is the Mumm-Ra script!
# Get ready to turn you machine into an awesome development one.
# Based on thoughtbot's awesome https://github.com/thoughtbot/laptop.

# The Incantation
echo
echo 'Ancient spirits of evil...'
echo "Transform $(hostname -s)'s decayed form..."
echo 'To Mumm-Ra, the Ever-living development machine!'
echo

read -r -s -n1 -p 'When ready, press any key to continue...'
echo
echo

# Setting up Homebrew
if ! command -v 'brew' >/dev/null 2>&1; then
  echo -n 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" >/dev/null 2>&1
else
  echo -n 'Homebrew is already installed. Updating it...'
  brew update >/dev/null 2>&1
fi

echo ' done.'
echo

formulae=( 'tree' 'wget' 'unrar' 'rbenv' 'ruby-build' 'shellcheck' )

for formula in "${formulae[@]}"; do

  if ! command -v "${formula}" >/dev/null 2>&1; then
    echo -n "Installing ${formula}..."
  else
    echo -n "Updating ${formula}..."
  fi

  brew install "${formula}" >/dev/null 2>&1
  echo ' done.'
done

echo

# Setting up Ruby-related stuff
latest_ruby_version="$(rbenv install -l | grep -v - | tail -1 | sed -e 's/^ *//')"

echo -n "Installing ruby ${latest_ruby_version}..."
if ! rbenv versions | grep -Fq "${latest_ruby_version}"; then
  rbenv install -s "${latest_ruby_version}" >/dev/null 2>&1
fi
echo ' done.'
echo

echo -n 'Configuring rbenv...'

bash_profile="${HOME}/.bash_profile"
rbenv_integration='eval "$(rbenv init -)"'

if [[ ! -f "${bash_profile}" ]]; then
  touch "${bash_profile}"
fi

if ! grep -Fqs "${rbenv_integration}" "${bash_profile}"; then
  echo "" >> "${bash_profile}"
  echo "${rbenv_integration}" >> "${bash_profile}"
fi

eval "$(rbenv init -)"

rbenv global "${latest_ruby_version}" >/dev/null 2>&1
rbenv shell "${latest_ruby_version}" >/dev/null 2>&1
echo ' done.'
echo

echo -n 'Updating RubyGems...'
gem update --system --no-document --silent
echo ' done.'
echo

gems=( 'bundler' )

for gem in "${gems[@]}"; do

  if gem list "${gem}" --no-installed >/dev/null 2>&1; then
    echo -n "Installing ${gem}..."
    gem install --no-document --quiet "${gem}"
    rbenv rehash
  else
    echo -n "Updating ${gem}..."
    gem update --no-document --quiet "${gem}"
  fi

  echo ' done.'
done

number_of_cores="$(sysctl -n hw.ncpu)"
bundle config --global jobs "$((number_of_cores - 1))"

# Run local customizations, if any
customizations="${HOME}/.mumm-ra.local"

if [[ -f "${customizations}" ]]; then
  echo "Now running your customizations from ${customizations}..."
  . "${customizations}"
  echo ' done.'
fi

echo
echo 'All good, enjoy!'
exit 0
